version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432' 

  backend:
    build:
      context: ./invoice-api # Path to your backend Dockerfile
    environment:
      DATABASE_URL: "postgresql://test_user:test123@db:5432/mydb?schema=public"
      JWT_SECRET: "secret123"
    depends_on:
      - db
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./invoice-app # Path to your frontend Dockerfile
    ports:
      - '3001:3001' # Map your frontend port

volumes:
  db_data:
