services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1005aaaa
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" 

  backend:
    build:
      context: ./invoice-api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:1005aaaa@db:5432/mydb?schema=public"
      JWT_SECRET: "secret123"
    ports:
      - "3000:3000"  
    depends_on:
      - db

  frontend:
    build:
      context: ./invoice-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
 
